# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EXESpriteReader.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1200, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.baseHLayout = QtGui.QHBoxLayout()
        self.baseHLayout.setObjectName(_fromUtf8("baseHLayout"))
        self.spriteLayout = QtGui.QVBoxLayout()
        self.spriteLayout.setObjectName(_fromUtf8("spriteLayout"))
        self.spriteLabel = QtGui.QLabel(self.centralwidget)
        self.spriteLabel.setObjectName(_fromUtf8("spriteLabel"))
        self.spriteLayout.addWidget(self.spriteLabel)
        self.spriteList = QtGui.QListWidget(self.centralwidget)
        self.spriteList.setMinimumSize(QtCore.QSize(300, 0))
        self.spriteList.setMaximumSize(QtCore.QSize(400, 16777215))
        self.spriteList.setObjectName(_fromUtf8("spriteList"))
        self.spriteLayout.addWidget(self.spriteList)
        self.baseHLayout.addLayout(self.spriteLayout)
        self.graphicsLayout = QtGui.QVBoxLayout()
        self.graphicsLayout.setObjectName(_fromUtf8("graphicsLayout"))
        self.graphicsLabel = QtGui.QLabel(self.centralwidget)
        self.graphicsLabel.setObjectName(_fromUtf8("graphicsLabel"))
        self.graphicsLayout.addWidget(self.graphicsLabel)
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(500, 0))
        brush = QtGui.QBrush(QtGui.QColor(200, 220, 255))
        brush.setStyle(QtCore.Qt.CrossPattern)
        self.graphicsView.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView.setForegroundBrush(brush)
        self.graphicsView.setInteractive(False)
        self.graphicsView.setResizeAnchor(QtGui.QGraphicsView.NoAnchor)
        self.graphicsView.setViewportUpdateMode(QtGui.QGraphicsView.FullViewportUpdate)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.graphicsLayout.addWidget(self.graphicsView)
        self.baseHLayout.addLayout(self.graphicsLayout)
        self.animLayout = QtGui.QVBoxLayout()
        self.animLayout.setObjectName(_fromUtf8("animLayout"))
        self.animLabel = QtGui.QLabel(self.centralwidget)
        self.animLabel.setObjectName(_fromUtf8("animLabel"))
        self.animLayout.addWidget(self.animLabel)
        self.animList = QtGui.QListWidget(self.centralwidget)
        self.animList.setMinimumSize(QtCore.QSize(150, 0))
        self.animList.setObjectName(_fromUtf8("animList"))
        self.animLayout.addWidget(self.animList)
        self.frameLabel = QtGui.QLabel(self.centralwidget)
        self.frameLabel.setObjectName(_fromUtf8("frameLabel"))
        self.animLayout.addWidget(self.frameLabel)
        self.frameList = QtGui.QListWidget(self.centralwidget)
        self.frameList.setMinimumSize(QtCore.QSize(150, 0))
        self.frameList.setObjectName(_fromUtf8("frameList"))
        self.animLayout.addWidget(self.frameList)
        self.animCheck = QtGui.QCheckBox(self.centralwidget)
        self.animCheck.setObjectName(_fromUtf8("animCheck"))
        self.animLayout.addWidget(self.animCheck)
        self.baseHLayout.addLayout(self.animLayout)
        self.oamLayout = QtGui.QVBoxLayout()
        self.oamLayout.setObjectName(_fromUtf8("oamLayout"))
        self.oamLabel = QtGui.QLabel(self.centralwidget)
        self.oamLabel.setObjectName(_fromUtf8("oamLabel"))
        self.oamLayout.addWidget(self.oamLabel)
        self.oamList = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oamList.sizePolicy().hasHeightForWidth())
        self.oamList.setSizePolicy(sizePolicy)
        self.oamList.setObjectName(_fromUtf8("oamList"))
        self.oamLayout.addWidget(self.oamList)
        self.palLabel = QtGui.QLabel(self.centralwidget)
        self.palLabel.setObjectName(_fromUtf8("palLabel"))
        self.oamLayout.addWidget(self.palLabel)
        self.palList = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.palList.sizePolicy().hasHeightForWidth())
        self.palList.setSizePolicy(sizePolicy)
        self.palList.setMinimumSize(QtCore.QSize(200, 300))
        self.palList.setMaximumSize(QtCore.QSize(16777215, 300))
        self.palList.setProperty("isWrapping", False)
        self.palList.setObjectName(_fromUtf8("palList"))
        self.oamLayout.addWidget(self.palList)
        self.palSelect = QtGui.QSpinBox(self.centralwidget)
        self.palSelect.setObjectName(_fromUtf8("palSelect"))
        self.oamLayout.addWidget(self.palSelect)
        self.palSaveButton = QtGui.QPushButton(self.centralwidget)
        self.palSaveButton.setObjectName(_fromUtf8("palSaveButton"))
        self.oamLayout.addWidget(self.palSaveButton)
        self.baseHLayout.addLayout(self.oamLayout)
        self.horizontalLayout.addLayout(self.baseHLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName(_fromUtf8("fileMenu"))
        self.spriteMenu = QtGui.QMenu(self.menubar)
        self.spriteMenu.setObjectName(_fromUtf8("spriteMenu"))
        self.helpMenu = QtGui.QMenu(self.menubar)
        self.helpMenu.setObjectName(_fromUtf8("helpMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.openAction = QtGui.QAction(MainWindow)
        self.openAction.setObjectName(_fromUtf8("openAction"))
        self.saveAction = QtGui.QAction(MainWindow)
        self.saveAction.setObjectName(_fromUtf8("saveAction"))
        self.exitAction = QtGui.QAction(MainWindow)
        self.exitAction.setObjectName(_fromUtf8("exitAction"))
        self.dumpAction = QtGui.QAction(MainWindow)
        self.dumpAction.setObjectName(_fromUtf8("dumpAction"))
        self.replaceAction = QtGui.QAction(MainWindow)
        self.replaceAction.setObjectName(_fromUtf8("replaceAction"))
        self.linkAction = QtGui.QAction(MainWindow)
        self.linkAction.setObjectName(_fromUtf8("linkAction"))
        self.aboutAction = QtGui.QAction(MainWindow)
        self.aboutAction.setObjectName(_fromUtf8("aboutAction"))
        self.openSpriteAction = QtGui.QAction(MainWindow)
        self.openSpriteAction.setObjectName(_fromUtf8("openSpriteAction"))
        self.repointAction = QtGui.QAction(MainWindow)
        self.repointAction.setCheckable(False)
        self.repointAction.setObjectName(_fromUtf8("repointAction"))
        self.saveImageAction = QtGui.QAction(MainWindow)
        self.saveImageAction.setObjectName(_fromUtf8("saveImageAction"))
        self.fileMenu.addAction(self.openAction)
        self.fileMenu.addAction(self.openSpriteAction)
        self.fileMenu.addAction(self.saveAction)
        self.fileMenu.addAction(self.exitAction)
        self.spriteMenu.addAction(self.dumpAction)
        self.spriteMenu.addAction(self.repointAction)
        self.spriteMenu.addAction(self.replaceAction)
        self.spriteMenu.addAction(self.saveImageAction)
        self.helpMenu.addAction(self.linkAction)
        self.helpMenu.addAction(self.aboutAction)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.spriteMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.openAction, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.openFile)
        QtCore.QObject.connect(self.spriteList, QtCore.SIGNAL(_fromUtf8("currentRowChanged(int)")), MainWindow.guiSpriteItemActivated)
        QtCore.QObject.connect(self.animList, QtCore.SIGNAL(_fromUtf8("currentRowChanged(int)")), MainWindow.guiAnimItemActivated)
        QtCore.QObject.connect(self.frameList, QtCore.SIGNAL(_fromUtf8("currentRowChanged(int)")), MainWindow.guiFrameItemActivated)
        QtCore.QObject.connect(self.openSpriteAction, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.openSprite)
        QtCore.QObject.connect(self.exitAction, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.dumpAction, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.dumpSprite)
        QtCore.QObject.connect(self.saveImageAction, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.saveFrameImage)
        QtCore.QObject.connect(self.palSelect, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.changePalet)
        QtCore.QObject.connect(self.palList, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QListWidgetItem*)")), MainWindow.guiPalItemActivated)
        QtCore.QObject.connect(self.saveAction, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.saveRomFile)
        QtCore.QObject.connect(self.oamList, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QListWidgetItem*)")), MainWindow.guiOAMItemActivated)
        QtCore.QObject.connect(self.repointAction, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.repoint)
        QtCore.QObject.connect(self.palSaveButton, QtCore.SIGNAL(_fromUtf8("pressed()")), MainWindow.writePalData)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ロックマンエグゼ スプライトリーダー by ideal", None))
        self.spriteLabel.setText(_translate("MainWindow", "スプライト", None))
        self.graphicsLabel.setText(_translate("MainWindow", "スプライトビュー", None))
        self.animLabel.setText(_translate("MainWindow", "アニメーション", None))
        self.frameLabel.setText(_translate("MainWindow", "フレーム", None))
        self.animCheck.setText(_translate("MainWindow", "アニメーション再生", None))
        self.oamLabel.setText(_translate("MainWindow", "OAM", None))
        self.palLabel.setText(_translate("MainWindow", "パレット", None))
        self.palSaveButton.setText(_translate("MainWindow", "編集したパレットを書き込む", None))
        self.fileMenu.setTitle(_translate("MainWindow", "ファイル", None))
        self.spriteMenu.setTitle(_translate("MainWindow", "スプライト", None))
        self.helpMenu.setTitle(_translate("MainWindow", "ヘルプ", None))
        self.openAction.setText(_translate("MainWindow", "ROMファイルを開く", None))
        self.openAction.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.saveAction.setText(_translate("MainWindow", "名前をつけてROMを保存", None))
        self.saveAction.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.exitAction.setText(_translate("MainWindow", "終了", None))
        self.exitAction.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.dumpAction.setText(_translate("MainWindow", "ダンプ", None))
        self.dumpAction.setStatusTip(_translate("MainWindow", "選択しているスプライトをファイルに出力します", None))
        self.replaceAction.setText(_translate("MainWindow", "置き換え", None))
        self.replaceAction.setStatusTip(_translate("MainWindow", "選択しているスプライトをファイルから読み込んだスプライトで上書きします", None))
        self.linkAction.setText(_translate("MainWindow", "リンク", None))
        self.aboutAction.setText(_translate("MainWindow", "このツールについて", None))
        self.openSpriteAction.setText(_translate("MainWindow", "スプライトを開く", None))
        self.openSpriteAction.setShortcut(_translate("MainWindow", "Ctrl+Shift+O", None))
        self.repointAction.setText(_translate("MainWindow", "リポイント", None))
        self.repointAction.setToolTip(_translate("MainWindow", "選択しているスプライトのポインタを書き換えて\n"
"別のアドレスのスプライトを読み込ませることが出来ます", None))
        self.repointAction.setStatusTip(_translate("MainWindow", "選択しているスプライトのポインタを書き換えて，別のアドレスのスプライトを読み込ませることが出来ます", None))
        self.saveImageAction.setText(_translate("MainWindow", "現在のフレームを画像に出力", None))

