# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MapModder.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(938, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.listLayout = QtGui.QVBoxLayout()
        self.listLayout.setObjectName(_fromUtf8("listLayout"))
        self.dataLabel = QtGui.QLabel(self.centralwidget)
        self.dataLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.dataLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.dataLabel.setObjectName(_fromUtf8("dataLabel"))
        self.listLayout.addWidget(self.dataLabel)
        self.dataList = QtGui.QListWidget(self.centralwidget)
        self.dataList.setMinimumSize(QtCore.QSize(200, 0))
        self.dataList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.dataList.setObjectName(_fromUtf8("dataList"))
        self.listLayout.addWidget(self.dataList)
        self.horizontalLayout_2.addLayout(self.listLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.graphicsLabel = QtGui.QLabel(self.centralwidget)
        self.graphicsLabel.setObjectName(_fromUtf8("graphicsLabel"))
        self.verticalLayout_2.addWidget(self.graphicsLabel)
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setMinimumSize(QtCore.QSize(500, 0))
        brush = QtGui.QBrush(QtGui.QColor(200, 220, 255))
        brush.setStyle(QtCore.Qt.CrossPattern)
        self.graphicsView.setBackgroundBrush(brush)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.palLayout = QtGui.QVBoxLayout()
        self.palLayout.setObjectName(_fromUtf8("palLayout"))
        self.palLabel = QtGui.QLabel(self.centralwidget)
        self.palLabel.setObjectName(_fromUtf8("palLabel"))
        self.palLayout.addWidget(self.palLabel)
        self.palList = QtGui.QListWidget(self.centralwidget)
        self.palList.setMinimumSize(QtCore.QSize(200, 0))
        self.palList.setObjectName(_fromUtf8("palList"))
        self.palLayout.addWidget(self.palList)
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.palLayout.addWidget(self.checkBox_2)
        self.verticalLayout_3.addLayout(self.palLayout)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.labelEdit = QtGui.QLineEdit(self.centralwidget)
        self.labelEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.labelEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.labelEdit.setObjectName(_fromUtf8("labelEdit"))
        self.gridLayout.addWidget(self.labelEdit, 0, 1, 1, 1)
        self.addrBox = QtGui.QSpinBox(self.centralwidget)
        self.addrBox.setMaximum(100000000)
        self.addrBox.setObjectName(_fromUtf8("addrBox"))
        self.gridLayout.addWidget(self.addrBox, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.palAddrBox = QtGui.QSpinBox(self.centralwidget)
        self.palAddrBox.setMaximum(100000000)
        self.palAddrBox.setSingleStep(32)
        self.palAddrBox.setObjectName(_fromUtf8("palAddrBox"))
        self.gridLayout.addWidget(self.palAddrBox, 2, 1, 1, 1)
        self.yTileBox = QtGui.QSpinBox(self.centralwidget)
        self.yTileBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.yTileBox.setMinimum(1)
        self.yTileBox.setObjectName(_fromUtf8("yTileBox"))
        self.gridLayout.addWidget(self.yTileBox, 4, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.xTileBox = QtGui.QSpinBox(self.centralwidget)
        self.xTileBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.xTileBox.setMinimum(1)
        self.xTileBox.setObjectName(_fromUtf8("xTileBox"))
        self.gridLayout.addWidget(self.xTileBox, 3, 1, 1, 1)
        self.compCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.compCheckBox.setEnabled(False)
        self.compCheckBox.setText(_fromUtf8(""))
        self.compCheckBox.setObjectName(_fromUtf8("compCheckBox"))
        self.gridLayout.addWidget(self.compCheckBox, 5, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.regButton = QtGui.QPushButton(self.centralwidget)
        self.regButton.setMinimumSize(QtCore.QSize(150, 0))
        self.regButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.regButton.setObjectName(_fromUtf8("regButton"))
        self.gridLayout.addWidget(self.regButton, 6, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.addrStep = QtGui.QSpinBox(self.centralwidget)
        self.addrStep.setMinimum(1)
        self.addrStep.setMaximum(100000)
        self.addrStep.setObjectName(_fromUtf8("addrStep"))
        self.gridLayout.addWidget(self.addrStep, 1, 3, 1, 1)
        self.palAddrstep = QtGui.QSpinBox(self.centralwidget)
        self.palAddrstep.setMinimum(1)
        self.palAddrstep.setMaximum(100000)
        self.palAddrstep.setProperty("value", 32)
        self.palAddrstep.setObjectName(_fromUtf8("palAddrstep"))
        self.gridLayout.addWidget(self.palAddrstep, 2, 3, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 938, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.dataList, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QListWidgetItem*)")), MainWindow.guiDataItemActivated)
        QtCore.QObject.connect(self.regButton, QtCore.SIGNAL(_fromUtf8("pressed()")), MainWindow.guiRegButtonPressed)
        QtCore.QObject.connect(self.palList, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QListWidgetItem*)")), MainWindow.guiPalItemActivated)
        QtCore.QObject.connect(self.palAddrBox, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.guiPalLineEdited)
        QtCore.QObject.connect(self.addrBox, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.guiAddrEdited)
        QtCore.QObject.connect(self.addrStep, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.guiAddrStepChanged)
        QtCore.QObject.connect(self.palAddrstep, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.guiPalAddrStepChanged)
        QtCore.QObject.connect(self.xTileBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.guiTileXChanged)
        QtCore.QObject.connect(self.yTileBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.guiTileYChanged)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Map Modder ver 0.1 by ideal.exe", None))
        self.dataLabel.setText(_translate("MainWindow", "登録データ", None))
        self.graphicsLabel.setText(_translate("MainWindow", "イメージ", None))
        self.palLabel.setText(_translate("MainWindow", "パレット", None))
        self.checkBox_2.setText(_translate("MainWindow", "グレースケール", None))
        self.label_4.setText(_translate("MainWindow", "リストに登録", None))
        self.label_9.setText(_translate("MainWindow", "Step", None))
        self.label_3.setText(_translate("MainWindow", "Step", None))
        self.label_5.setText(_translate("MainWindow", "ラベル", None))
        self.label_8.setText(_translate("MainWindow", "圧縮", None))
        self.label_2.setText(_translate("MainWindow", "Y", None))
        self.label_6.setText(_translate("MainWindow", "アドレス", None))
        self.label_7.setText(_translate("MainWindow", "パレット", None))
        self.regButton.setText(_translate("MainWindow", "リストに登録", None))
        self.label.setText(_translate("MainWindow", "X", None))
        self.menu.setTitle(_translate("MainWindow", "ファイル", None))

